### ISSUE TITLE
Directory listing enabled?

### ISSUE THREAD

**Issue by eirslett** [cybernetisk/drift#11]
Prøv

1) Gå inn på google.com
2) Søk på `intitle:"index of" site:"cyb.no"`

Kan hende at det ikke er meningen at man skal kunne liste ut alle de filene der?

**Comment by N0K0** [comment]
Hmm, er jo ikke egentlig et problem. Er jo gammelweb filer som er eksponert. Er ingenting sensitivt der og øker jo egentlig bare hvor enkelt det er å finne gammel moro :tada:
