### ISSUE TITLE
https med LetsEncrypt

### ISSUE THREAD

**Issue by dizzi90** [cybernetisk/drift#5]
Forventet interaksjon:
Gå til cyb.no
Bli redirectiet til https://cyb.no
Ha godkjent SSL-kobling.

Faktisk interaksjon:
Gå til cyb.no
Får ikke SSL.
Endrer manuelt til https.
Får ikke-godkjent sertifikat.

Endringsforslag:
Sett opp redirection og LetsEncrypt for gratis automatisert oppdatering av sertifikat. Se https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04 for instruksjoner.

**Comment by adriah** [comment]
Slik det er nå blir cyb.no hostet av Ifi. De har ikke støtte for SSL-kobling på web-serveren sin (blir servert gjennom folk.uio.no biten) for tiden. 

Sant skal sies at det jobbes med en løsning for å flytte dette over på en annen instans som lar oss sette opp let's encrypt, slik som resten av løsningene til CYB gjør. Vi har rett og slett for mange "legacy" redirect scripts og annet knask fra 90-tallet liggende der 😄

**Comment by adriah** [comment]
En annen ting som er verdt å nevne er at siden kun inneholder statisk innhold, og tar ikke inn noe informasjon fra brukeren. Derfor er det heller ikke noe stort "behov" for SSL 😉

**Comment by thor** [comment]
> En annen ting som er verdt å nevne er at siden kun inneholder statisk innhold, og tar ikke inn noe informasjon fra brukeren. Derfor er det heller ikke noe stort "behov" for SSL wink

Joda, men det hadde jo fortsatt vært fint å vite at ingen har tuklet med siden, samtidig som man for ytelsesforbedringene som kommer med HTTP/2. :upside_down_face:

**Comment by thor** [comment]
Fikset med Netlify! :heart:
